name: Semgrep Snyk and Truffle Pig Scans

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  trufflehog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Secret Scanning with TruffleHog
        uses: trufflesecurity/trufflehog@main
        with:
          extra_args: --only-verified

  SCA-Snyk:
    needs: [trufflehog]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build a Docker image
        run: docker build -t node-goat:latest .
      - name: Run Snyk to check Docker image for vulnerabilities
        continue-on-error: true
        uses: snyk/actions/docker@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          image: node-goat:latest
          args: --file=Dockerfile --serif-file-output=snyk.sarif
      - name: Upload Snyk SARIF report
        uses: actions/upload-artifact@v3
        with:
          name: snyk-sca.sarif
          path: snyk.sarif

  SAST-Semgrep:
    needs: [trufflehog]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run Semgrep Scan
        run: |
          docker run --rm -v "${{ github.workspace }}:/src" returntocorp/semgrep semgrep --config=p/r2c-ci --sarif --output=/src/semgrep-sast.sarif /src

      - name: Upload Semgrep SARIF report
        uses: actions/upload-artifact@v3
        with:
          name: semgrep-sast.sarif
          path: semgrep-sast.sarif
